routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


//Polls
Route::resource('/poll', 'PollController');

//Options
Route::get('poll/{poll}/options/add', ['uses' => 'OptionController@push', 'as' => 'poll.options.push']);
Route::post('poll/{poll}/options/add', ['uses' => 'OptionController@add', 'as' => 'poll.options.add']);
Route::get('poll/{poll}/options/remove', ['uses' => 'OptionController@delete', 'as' => 'poll.options.remove']);
Route::delete('poll/{poll}/options/remove', ['uses' => 'OptionController@remove', 'as' => 'poll.options.remove']);

//Vote
Route::post('/poll/vote/{poll}', ['uses' => 'OptionController@vote', 'as' => 'poll.vote']);
Route::get('poll/vote/{poll}',['uses' => 'PollController@getVotesView', 'as' => 'poll.vote']);

//Dashboard redirect
Route::get('/', function () {
    return redirect(route('poll.index'));
});

app/Poll.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Poll extends Model
{
    protected $fillable = ['question'];
    protected $options_add = [];
    protected $maxSelection = 1;
    /**
     * A poll has many options related to
     *
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     */
    public function options()
    {
        return $this->hasMany(Option::class);
    }
    public function getAllOptions($id)
    {
        $allpictures = $this->options()->where('poll_id', $id)->get();
        foreach($allpictures as $pic){
            $currPath[] = $pic;
        }
        return $currPath;
    }

    public function countVotes($id)
    {
        $allVotes = $this->options()->where('poll_id', $id)->get();
        $votes_sum = null;
        foreach($allVotes as $vote){
            $votes_sum += $vote->votes;
        }
        return $votes_sum;
    }

    public function optionsNumber()
    {
        return $this->options()->count();
    }

    /**
     * Creating new Poll
     *
     * @return App\Poll;
     */
    public static function createFromRequest($request)
    {
        $poll = new Poll([
            'question' => $request['question']
        ]);
        $poll->addOptions($request['options']);
        if(array_key_exists('maxCheck', $request)){
            $poll->maxSelection($request['maxCheck']);
        }
        $poll->generate();
        return $poll;
    }

    public function maxSelection($number = 1)
    {
        if($number <= 1){
            $number = 1;
        }
        $this->maxSelection = $number;
        return $this;
    }

    public function addOptions($options)
    {
        if(is_array($options))
        {
            foreach($options as $option){
                if(is_string($option)){
                    $this->pushOption($option);
                }else{
                    throw new \InvalidArgumentException("Array arguments must be composed of Strings values");
                }
            }
            return $this;
        }
        if(is_string($options)){
            $this->pushOption($options);
            return $this;
        }
        throw new \InvalidArgumentException("Invalid Argument provided");
    }

    private function pushOption($option)
    {
        if(! in_array($option, $this->options_add)){
            $this->options_add[] = $option;
            return true;
        }
        return false;
    }
    public function generate()
    {
        $totalOptions = count($this->options_add);
        // No option add yet
        if($totalOptions == 0)
            throw new OptionsNotProvidedException();
        // There must be 2 options at least
        if($totalOptions == 1 )
            throw new OptionsInvalidNumberProvidedException();
        // At least one options should not be selected
        if($totalOptions <= $this->maxSelection )
            throw new CheckedOptionsException();
        // Create Poll && assign options to it
        \DB::transaction(function () {
            $this->maxCheck = $this->maxSelection;
            $this->save();
            $this->options()
                ->saveMany($this->instantiateOptions());
        });
        return true;
    }

    private function instantiateOptions()
    {
        $options = [];
        foreach($this->options_add as $option){
            $options[] = new Option([
                'name' => $option
            ]);
        }
        return $options;
    }

    public function attach($options)
    {
        
        if(is_array($options))
        {
            $newOptions = [];
            foreach($options as $option){
                if(is_string($option)){
                    $newOptions[] = new Option([
                        'name' => $option
                    ]);
                }else{
                    throw new \InvalidArgumentException("Array arguments must be composed of Strings values");
                }
            }
            return $this->options()->saveMany($newOptions);
        }
        if(is_string($options)){
            return $this->options()->save(
                new Option([
                    'name' => $options
                ])
            );
        }
        throw new \InvalidArgumentException("Invalid Argument provided");
    }

    /**
     * Remove a (list of elements)
     *
     * @param $options
     * @return bool
     * @throws CheckedOptionsException
     * @throws InvalidArgumentException
     */
    public function detach($options)
    {
        // Prepare the elements as an array
        $options = is_array($options) ? $options : func_get_args();
        $oldOptions = [];
        $elements = $this->options()->pluck('id');
        foreach($options as $option){
            if(is_numeric($option) && is_int(intval($option))){
                $option = intval($option);
                $option = Option::findOrFail($option);
                if($this->containsAndNotVoted($elements, $option->id)){
                    $oldOptions[] = $option->id;
                }
            }else if($option instanceof Option){
                if($this->containsAndNotVoted($elements, $option->getKey())) {
                    $oldOptions = $option->getKey();
                }
            }else {
                throw new \InvalidArgumentException("Array arguments must be composed of ids or option object values");
            }
        }
        // verify the number of options
        
        $diff = ($elements->count() - count($oldOptions));
        if($this->isRadio()){
            $count = count($oldOptions);
            return Option::destroy($oldOptions) == $count;
        }
        // checkbox case
        if($diff <= $this->maxCheck)
            throw new CheckedOptionsException();
        $count = count($oldOptions);
        return Option::destroy($oldOptions) == $count;
    }

    private function containsAndNotVoted($elements, $against)
    {
        return $elements->contains($against);
    }
    public function isRadio()
    {
        return $this->maxCheck == 1;
    }

    protected $poll;
    /**
     * Select poll
     *
     * @param Poll $poll
     * @return $this
     */
    public function poll(Poll $poll)
    {
        $this->poll = $poll;
        return $this;
    }
    public function results()
    {
        $this->results = collect();
        foreach($this->options()->get() as $option){
            $this->results->push([
              "option" => $option,
              "votes" => $option->countVotes(),
            ]);
        }
        return $this;
    }
    public function grab()
    {
        if(! is_null($this->results)){
            return $this->results->toArray();
        }
    }
}

app/Http/Controllers/PollController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Poll;

class PollController extends Controller
{
    /**
     * Show all the Polls in the database
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $polls = Poll::withCount('options')->get();
        return view('polls.dashboard', compact('polls'));
    }
    /**
     * Store the Request
     *
     * @param PollCreationRequest $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function store(Request $request)
    {
        $poll = Poll::createFromRequest($request->all());
        return redirect(route('poll.index'))
            ->with('success', 'Your poll has been addedd successfully');
    }
    /**
     * Show the poll to be prepared to edit
     *
     * @param Poll $poll
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit(Poll $poll)
    {
        return view('polls.edit', compact('poll'));
    }
    /**
     * Update the Poll
     *
     * @param Poll $poll
     * @param Request $request
     * @return \Illuminate\Http\RedirectResponse
     */
    public function update(Poll $poll, Request $request)
    {
        $poll->update($request->all());

        return redirect(route('poll.index'))
            ->with('success', 'Your poll has been updated successfully');
    }
    /**
     * Delete a Poll
     *
     * @param Poll $poll
     * @return \Illuminate\Http\RedirectResponse
     */
    public function destroy(Poll $poll)
    {
        $poll->options()->delete();
        $poll->delete();
        return redirect(route('poll.index'))
            ->with('success', 'Your poll has been deleted successfully');
    }
    public function create()
    {
        return view('polls.create');
    }

    public function show($id){
        $poll = Poll::findOrFail($id);
        $total = $poll->countVotes($id);

        return view('polls.show_results')
            ->with('poll',$poll)
            ->with('total',$total);
    }
    public function getVotesView($id){
        $poll = Poll::findOrFail($id);

        return view('polls.vote')
            ->with('poll',$poll);
    }
}

resources/views/polls/create.blade.php
@extends('templates.base')
@section('title')
    Polls- Creation
@endsection
@section('content')
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{{ route('poll.index') }}">Polls</a></li>
            <li class="active">Create New Poll</li>
        </ol>
    <div class="well col-md-8 col-md-offset-2">
            @if($errors->any())
                <ul class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
        <form method="POST" action=" {{ route('poll.store') }}">
            {{ csrf_field() }}
            <!-- Question Input -->
            <div class="col-sm-12" id="create_poll_form">
                <label for="question" class="col-md-2 control-label">Question:</label>
                <div class="col-md-10 form-group">
                <input id="question" type="text" name="question" class="form-control" required/>
                </div>
                <label for="options[0]" class="col-md-2 control-label">Option 1:</label>
                <div class="col-md-10 form-group">
                    <input type="text" name="options[0]" class="form-control" required/>
                </div>
                <label for="options[1]" class="col-md-2 control-label">Option 2:</label>
                <div class="col-md-10 form-group">
                    <input type="text" name="options[1]" class="form-control" required/>
                </div>
            </div>
            <!-- Create Form Submit -->
            <div class="form-group col-sm-3 pull-right">
                <input name="create" type="submit" value="Create" class="btn btn-primary form-control"/>
            </div>
        </form>
            <a class="btn btn-success" id="add">
                <i class="fa fa-plus-circle" aria-hidden="true"></i>
            </a>
    </div>
</div>
@endsection

@section('js')
    <script type="text/javascript">
        function remove(current){
            debugger;
            $('#label'+current.parentNode.id).remove();
            current.parentNode.remove();
        }
        var $counter = 3;
        document.getElementById("add").onclick = function() {
            // create label
            var e1 = document.createElement('label');
            e1.className = ('col-md-2 control-label');
            e1.id = ('label'+$counter);
            e1.innerText = ('Option'+$counter+':');
            //create input field
            var e = document.createElement('div');
            e.className = ('col-md-10 form-group');
            e.id= ($counter);
            e.innerHTML = "<input type='text' name='options[]' class='form-control add-input' required /> <a class='btn btn-danger' href='#' onclick='remove(this)'><i class='fa fa-minus-circle' aria-hidden='true'></i></a>";
            //append document
            document.getElementById("create_poll_form").appendChild(e1);
            document.getElementById("create_poll_form").appendChild(e);
            //increment counter
            $counter = $counter+1;
        }
    </script>
@endsection

resources/views/polls/dashboard.blade.php
@extends('templates.base')
@section('style')
    <style>
        .table td, .table th {
            text-align: center;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <ol class="breadcrumb">
            <li class="active"><a href="{{ route('poll.index') }}">Polls</a></li>
        </ol>
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif

        @if($polls->count() >= 1)
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Question</th>
                    <th>Options</th>
                    <th>Current Votes</th>
                    <th>Vote</th>
                    <th>View Results</th>
                    <th>Edit</th>
                    <th>Add Options</th>
                    <th>Remove Options</th>
                    <th>Remove Poll</th>
                </tr>
                </thead>
                <tbody>
                @forelse($polls as $poll)
                    <tr>
                        <th scope="row">{{ $poll->id }}</th>
                        <td><a href="{{ route('poll.vote', $poll->id) }}">{{ $poll->question }}</a></td>
                        <td>{{ $poll->options_count }}</td>
                        <td>{{ $poll->countVotes($poll->id) }}</td>
                        <td>
                            <a class="btn btn-default btn-sm" href="{{ route('poll.vote', $poll->id) }}">
                                <i class="fa fa-thumbs-up" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-default btn-sm" href="{{ route('poll.show', $poll->id) }}">
                                <i class="fa fa-eye" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-default btn-sm" href="{{ route('poll.edit', $poll->id) }}">
                                <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-default btn-sm" href="{{ route('poll.options.add', $poll->id) }}">
                                <i class="fa fa-plus-circle" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <a class="btn btn-default btn-sm" href="{{ route('poll.options.remove', $poll->id) }}">
                                <i class="fa fa-minus-circle" aria-hidden="true"></i>
                            </a>
                        </td>
                        <td>
                            <form action="{{ route('poll.destroy', $poll->id) }}" method="POST">
                                {{ csrf_field() }}
                                {{ method_field('DELETE') }}
                                <button type="submit" class="btn btn-danger btn-sm">
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </button>
                            </form>
                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <smal>No poll has been found. Try to add one <a href="{{ route('poll.create') }}">Now.</a></smal>
        @endif
    </div>
@endsection

resources/views/polls/edit.blade.php
@extends('templates.base')
@section('title')
    Polls- Edit
@endsection
@section('content')
    <div class="container">
        <ol class="breadcrumb">
            <li><a href="{{ route('poll.index') }}">Polls</a></li>
            <li class="active">Edit Poll</li>
        </ol>
        <div class="well col-md-8 col-md-offset-2">
            @if($errors->any())
                <ul class="alert alert-danger">
                    @foreach($errors->all() as $error)
                        <li>{{ $error }}</li>
                    @endforeach
                </ul>
            @endif
            <form method="POST" action=" {{ route('poll.update', $poll->id) }}">
                <input name="_method" type="hidden" value="PUT">
                {{ csrf_field() }}
                <!-- Question Input -->
                <div class="form-group">
                    <label><h4>Current Pool Question:&nbsp;{{ $poll->question }}</h4></label>
                </div>
                <div class="form-group">
                    <label><h5>Rename:</h5></label>
                    <input name="question" value="{{ $poll->question }}" class="form-control"/>
                </div>
                <!-- Create Form Submit -->
                <div class="form-group">
                    <div class="col-sm-6">
                        <input name="update" type="submit" value="Update" class="btn btn-primary form-control"/>
                    </div>
                    <div class="col-sm-6">
                        <a href="{{ route('poll.index') }}" class="btn btn-default form-control">Back</a>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/polls/poll_form.blade.php
<form method="POST" action="{{ route('poll.vote', $poll->id) }}">
{{ csrf_field() }}
    <div class="panel panel-primary">
        <div class="panel-heading">
            <h3 class="panel-title">
                <span class="glyphicon glyphicon-arrow-right"></span>{{$poll->question}}
            </h3>
        </div>
    </div>
    <div class="panel-body">
        <ul class="list-group">
            @foreach($poll->getAllOptions($poll->id) as $option)
                <li class="list-group-item">
                    <div class="radio">
                        <label>
                            <input value="{{$option->id}}" type="radio" name="options">
                            {{$option->name}}
                        </label>
                    </div>
                </li>
            @endforeach
        </ul>
    </div>
    <div class="panel-footer">
        <input type="submit" class="btn btn-primary btn-sm" value="Vote">
    </div>
</form>

resources/views/polls/show_results.blade.php
@extends('templates.base')
@section('style')
    <style>
        .table td, .table th {
            text-align: center;
        }
    </style>
@endsection
@section('content')
    <div class="container">
        <ul class="breadcrumb">
            <li><a href="{{ route('poll.index') }}">Polls</a></li>
            <li class="active">View current votes</li>
        </ul>
        @if(Session::has('success'))
            <div class="alert alert-success">
                {{ session('success') }}
            </div>
        @endif
        <div class="col-sm-12">
        <div class="row">
        <div class="col-sm-10">
            <h3>
                <strong>Poll: {{$poll->question}}</strong>
            </h3>
        </div>
            <div class="col-sm-2">
                <a href="{{ route('poll.index') }}" class="btn btn-primary pull-right">Back</a>
            </div>
        </div>
            @foreach($poll->getAllOptions($poll->id) as $option)
            @php
            $currVotes = $option->votes;
            if($total == 0){
                $percent = 0;
            }else{
                $percent = ($currVotes * 100) /($total);
            }
            @endphp
            <div class='result-option-id'>
                <strong>{{$option->name}}</strong><span class='pull-right'>{{round($percent, 0)}}%</span>
                <div class='progress'>
                    <div class='progress-bar progress-bar-striped active' role='progressbar' aria-valuenow='{{round($percent, 0)}}' aria-valuemin='0' aria-valuemax='100' style='width: {{round($percent, 0)}}%'>
                        <span class='sr-only'>{{round($percent, 0)}}% Complete</span>
                    </div>
                </div>
            </div>
            @endforeach
        </div>
        
    </div>
@endsection

resources/views/polls/vote.blade.php
@extends('templates.base')
@section('content')
    <div class="container">
        @if (isset($poll))
                <form method="POST" action="{{ route('poll.vote', $poll->id) }}">
                {{ csrf_field() }}
                    <div class="panel panel-primary">
                        <div class="panel-heading">
                                <h3 class="panel-title">
                                    <span class="glyphicon glyphicon-arrow-right"></span>{{$poll->question}}
                                </h3>
                        </div>
                    </div>
                    <div class="panel-body">
                        <ul class="list-group">
                            @foreach($poll->getAllOptions($poll->id) as $option)
                                <li class="list-group-item">
                                    <div class="radio">
                                        <label>
                                            <input value="{{$option->id}}" type="radio" name="options">
                                            {{$option->name}}
                                        </label>
                                    </div>
                                </li>
                            @endforeach
                        </ul>
                    </div>
                    <div class="panel-footer">
                        <input type="submit" class="btn btn-primary" value="Vote">
                        <a href="{{ route('poll.index') }}" class="btn btn-default">Back</a>
                    </div>
                </form>
                <hr>
        @endif
    </div>
@endsection